source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
use_frameworks!

target 'OznerLbFrameWork' do
    pod 'DateTools'
    pod 'MQTTKit'
    pod 'SwiftyJSON'
    pod 'SQLite.swift', '~> 0.11.3'
end

